

[colors]
[colors.primary]
background = "#101010"
foreground = "#d4d4d4"
dim_foreground = "#A0A0A0"

[colors.cursor]
text = "CellBackground"
cursor = "#ffffff"

[colors.selection]
text = "CellForeground"
background = "#232323"

[colors.normal]
black = "#101010"
red = "#FF8080"
green = "#99FFE4"
yellow = "#FFC799"
blue = "#FFC799"
magenta = "#FBADFF"
cyan = "#99FFE4"
white = "#e3e3dd"

[colors.bright]
black = "#101010"
red = "#FF8080"
green = "#99FFE4"
yellow = "#FFC799"
blue = "#FFC799"
magenta = "#FBADFF"
cyan = "#99FFE4"
white = "#f8f8f2"
