# Omarchy Custom Theme for Kitty
# Converted from the Alacritty theme

background #101010
foreground #d4d4d4
cursor #343434
cursor_text_color #ffffff
selection_background #232323
selection_foreground #d4d4d4

# Normal
color0  #101010
color1  #FF8080
color2  #99FFE4
color3  #FFC799
color4  #FFC799
color5  #FBADFF
color6  #99FFE4
color7  #e3e3dd

# Bright
color8  #101010
color9  #FF8080
color10 #99FFE4
color11 #FFC799
color12 #FFC799
color13 #FBADFF
color14 #99FFE4
color15 #f8f8f2
